---
fullname: Topology
shortname: topology
organization: coq-community
community: true
action: true

synopsis: General topology in Coq

description: |
  This library develops some of the basic concepts
  and results of set theory and general topology in Coq.

authors:
- name: Daniel Schepler
  e-mail: dschepler@gmail.com
  initial: true

maintainers:
- name: Andrew Miloradovsky
  nickname: amiloradovsky
- name: stop-cran
  nickname: stop-cran
- name: Columbus240
  nickname: Columbus240

opam-file-maintainer: palmskog@gmail.com

license:
  fullname: GNU Lesser General Public License v2.1 or later
  identifier: LGPL-2.1-or-later
  file: LICENSE

supported_coq_versions:
  text: Coq 8.10 or later (use the corresponding branch or release for other Coq versions)
  opam: '{(>= "8.10" & < "8.14~") | (= "dev")}'

tested_coq_nix_versions:
- version_or_url: https://github.com/coq/coq-on-cachix/tarball/master

tested_coq_opam_versions:
- version: dev
- version: '8.13'
- version: '8.12'
- version: '8.11'
- version: '8.10'

dependencies:
- opam:
    name: coq-zorns-lemma
    version: '{(>= "8.10" & < "8.14~") | (= "dev")}'
  nix: contribs.zorns-lemma
  description: |-
    [Zorn's lemma](https://github.com/coq-community/zorns-lemma)

namespace: Topology

keywords:
- name: set theory
- name: cardinals
- name: ordinals
- name: finite
- name: countable
- name: quotients
- name: well-orders
- name: Zorn's lemma

- name: topology
- name: filters
- name: nets
- name: metric spaces
- name: real analysis
- name: Urysohn's lemma
- name: Tietze extension theorem

categories:
- name: Mathematics/Real Calculus and Topology
- name: Mathematics/Logic/Set theory

documentation: |-
  ## Contents of ZornsLemma

  In alphabetical order, except where related files are grouped together:

  - `Cardinals.v` - cardinalities of sets
  - `Ordinals.v` - a construction of the ordinals without reference to well-orders

  - `Classical_Wf.v` - proofs of the classical equivalence of wellfoundedness, the minimal element property, and the descending sequence property

  - `CSB.v` - the Cantor-Schroeder-Bernstein theorem

  - `DecidableDec.v` - `classic_dec: forall P: Prop, {P} + {~P}.`

  - `DependentTypeChoice.v` - choice on a relation (`forall a: A, B a -> Prop`)

  - `EnsemblesImplicit.v` - settings for appropriate implicit parameters for the standard library's Ensembles functions
  - `ImageImplicit.v` - same for the standard library's Sets/Image
  - `Relation_Definitions_Implicit.v` - same for the standard library's Relation_Definitions

  - `EnsemblesSpec.v` - defines a notation for e.g. `[ n: nat | n > 5 /\ even n ] : Ensemble nat.`

  - `EnsemblesTactics.v` - defines tactics that help in proofs about Ensembles

  - `EnsemblesUtf8.v` - optional UTF-8 notations for set operations

  - `Families.v` - operations on families of subsets of `X`, i.e. `Ensemble (Ensemble X)`
  - `IndexedFamilies.v` - same for indexed families `A -> Ensemble X`

  - `FiniteIntersections.v` - defines the finite intersections of a family of subsets

  - `FiniteTypes.v` - definitions and results about finite types
  - `CountableTypes.v` - same for countable types
  - `InfiniteTypes.v` - same for infinite types

  - `FunctionProperties.v` - injective, surjective, etc.

  - `InverseImage.v` - inverse images of subsets under functions

  - `Powerset_facts.v` - some lemmas about the operations on subsets that the stdlib is missing

  - `Proj1SigInjective.v` - inclusion of `{ x: X | P x }` into `X` is injective

  - `Quotients.v` - quotients by equivalence relations, and induced functions on them

  - `WellOrders.v` - some basic properties of well-orders, including a proof that Zorn's Lemma implies the well-ordering principle

  - `ZornsLemma.v` - proof that choice implies Zorn's Lemma

  ## Contents of Topology, roughly grouped in related categories:

  ### Basic definitions

  - `TopologicalSpaces.v`
  - `InteriorsClosures.v`
  - `Neighborhoods.v`
  - `OpenBases.v`
  - `NeighborhoodBases.v`
  - `Subbases.v`
  - `Continuity.v`
  - `Homeomorphisms.v`

  ### Filters and nets

  - `Filters.v`
  - `FilterLimits.v`
  - `DirectedSets.v`
  - `Nets.v`
  - `FiltersAndNets.v` - various transformations between filters and nets

  ### Properties

  - `Compactness.v`
  - `Connectedness.v`
  - `CountabilityAxioms.v` - first countable, second countable, separable, Lindelof
  - `SeparatednessAxioms.v` - T0, T1, Hausdorff, etc.

  ### General constructions of topologies

  - `OrderTopology.v`
  - `StrongTopology.v` - strong topology induced by a family of maps from
  topological spaces
  - `WeakTopology.v` - weak topology induced by a family of maps to
  topological spaces
  - `ProductTopology.v`
  - `SumTopology.v` - also called "disjoint union" or "coproduct"
  - `SubspaceTopology.v`
  - `QuotientTopology.v`
  - `ContinuousFactorization.v` - a continuous map factors through its image

  ### Metric spaces

  - `MetricSpaces.v`
  - `Completeness.v`
  - `Completion.v`
  - `UniformTopology.v` - the topology of uniform convergence

  ### Real analysis

  - `SupInf.v`
  - `RationalsInReals.v`
  - `RTopology.v` - definition and properties of topology on R
  - `RFuncContinuity.v` - reproof of continuity of basic functions on R

  ### "First nontrivial results of topology"

  - `UrysohnsLemma.v`
  - `TietzeExtension.v`
---
